# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GEC.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GEC.proto',
  package='compute',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tGEC.proto\x12\x07\x63ompute\"\x1a\n\nGECRequest\x12\x0c\n\x04text\x18\x01 \x03(\t\"\x1a\n\x08GECReply\x12\x0e\n\x06result\x18\x01 \x03(\t2:\n\x07\x43ompute\x12/\n\x03GEC\x12\x13.compute.GECRequest\x1a\x11.compute.GECReply\"\x00\x62\x06proto3'
)




_GECREQUEST = _descriptor.Descriptor(
  name='GECRequest',
  full_name='compute.GECRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='compute.GECRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=48,
)


_GECREPLY = _descriptor.Descriptor(
  name='GECReply',
  full_name='compute.GECReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='compute.GECReply.result', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['GECRequest'] = _GECREQUEST
DESCRIPTOR.message_types_by_name['GECReply'] = _GECREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GECRequest = _reflection.GeneratedProtocolMessageType('GECRequest', (_message.Message,), {
  'DESCRIPTOR' : _GECREQUEST,
  '__module__' : 'GEC_pb2'
  # @@protoc_insertion_point(class_scope:compute.GECRequest)
  })
_sym_db.RegisterMessage(GECRequest)

GECReply = _reflection.GeneratedProtocolMessageType('GECReply', (_message.Message,), {
  'DESCRIPTOR' : _GECREPLY,
  '__module__' : 'GEC_pb2'
  # @@protoc_insertion_point(class_scope:compute.GECReply)
  })
_sym_db.RegisterMessage(GECReply)



_COMPUTE = _descriptor.ServiceDescriptor(
  name='Compute',
  full_name='compute.Compute',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=78,
  serialized_end=136,
  methods=[
  _descriptor.MethodDescriptor(
    name='GEC',
    full_name='compute.Compute.GEC',
    index=0,
    containing_service=None,
    input_type=_GECREQUEST,
    output_type=_GECREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPUTE)

DESCRIPTOR.services_by_name['Compute'] = _COMPUTE

# @@protoc_insertion_point(module_scope)
